<p>Creating a dynamic website is easy! All you need to do is allow the website to change with user input.</p>
<p>Dynamic content is generated by user interaction, such as filling out a form or clicking a button.</p>
<p>Static content is unchanging, like the header and footer! They can change, but only if the code is updated. In contrast, dynamic content can change greatly from visit to visit, without having to change any code at all!</p>
<p>You can also have multiple static pages dynamically displayed, instead of redirecting users to different pages. You do this by creating links that are parsable with GET.</p>
<p>For example, creating a link to index.php?page=cool would allow you to create a script which puts something cool on the page instead of whatever was on the page before! (cool content not included)</p>
